### ISSUE TITLE
Elrond .NET sdk - official version and add send bulk transactions

### ISSUE THREAD

**Issue by alexandrunguta** [ElrondNetwork/elrond-sdk-erdcsharp#4]
Hello! I've just noticed that the Elrond .Net sdk isn't available: https://github.com/ElrondNetwork/elrond-sdk-erdcsharp  (nuget package not found). From what I found there is another package which seems to be identical: https://github.com/yann4460/elrond-sdk.dotnet and now i'm using this one.
Please can you provide an official Elrond .Net sdk? Also I need the sending bulk transactions feature to be in place in this sdk because I need to make transactions from 1 wallet to multiple (100, 1000, etc).
Thank you in advance!

**Comment by schimih** [comment]
Hi @alexandru96 ,
it is not an official .NET sdk but is the most up to date one:
https://github.com/RemarkableTools/Mx.NET.SDK
